### ISSUE TITLE
KeyError: 'DOMAIN'

### ISSUE THREAD

**Issue by DanGarion** [nvllsvm/linode-dynamic-dns#9]
Hello I get the following error when attempting to run this.

Here is the docker run ---

 docker run \
    -e LINODE_ACCESS_TOKEN=XXXXXX \
    -e LINODE_DNS_DOMAIN=XXXXX.XXXXX\
    -e LINODE_DNS_HOSTNAME=* \
    nvllsvm/linode-dynamic-dns

Here is what is returned in the error message.

Traceback (most recent call last):
  File "/usr/local/bin/linode-dynamic-dns", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/linode_dynamic_dns/__main__.py",                                                                                                                                                              line 131, in main
    domain = os.environ['DOMAIN']
  File "/usr/local/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DOMAIN'

**Comment by andrewrabert** [comment]
Repull the image and your docker command should work. Fixed in 0.7.0.

**Comment by DanGarion** [comment]
I'll try it in the future if I go down this route again. For now, I have Caddy doing the dyn DNS stuff for me in my opnsense router.
